config/routes.rb
Rails.application.routes.draw do

  root to: "posts#index"
  
  get "admin/posts/new", to: "posts#new", as: "posts_new"
  post "posts", to: "posts#create"
  
  get "posts/edit/:id", to: "posts#edit", as: "posts_edit"
  patch "posts/edit/:id", to: "posts#update"

  get "posts/show/:id", to: "posts#show", as: "posts_show"

  post "post/:id/comments", to: "comments#create", as: "post_comments"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates_presence_of :title
	has_many :comments
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
	
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@comment = Comment.new
		render :new
	end

	#def create
	#	comment = Comment.create(post_id: params["id", body: params["body"]])
	#	redirect_to post_path(params["id"])
	#end

	def create
		@post = Post.find(params["id"])
		@post.comments.create(body: params["body"])
		redirect_to post_pat(@post)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.page(params[:page]).per(5)
	end

	def new
		render :new
	end

	def create
		new_post = Post.create(title: params["title"],
								content: params["content"])

		redirect_to :root
	end

	def edit
		render :edit
	end

	def update
		#this_post = Post.find(params[:id])
		#this_post.update( title: params["title"], content: params["content"])

		#redirect_to :root
		post = Post.find(params["id"])
		post.update(title: params["title"], content: params["content"])
	end

	def show
		@post = Post.find(params[:id])
		render :show #locals: { post: @post }
		#more common to see instance variables than locals in
		#controller methods
		#totally legal to do @post = Post.find(params["id"])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blarg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_tag(posts_edit_path, method: "patch") do %>
	<h1>Edit Post Here</h1>
	<div class="post-field">
	<%= label_tag("Title: ") %>
	<%= text_field_tag("title") %>
	</div>

	<div class="post-field">
		<%= label_tag("Content: ") %>
		<%= text_area_tag("content") %>
	</div>

	<%= button_tag("Save!") %>
<% end %>

app/views/posts/index.html.erb
<%= link_to("Add a new post!", posts_new_path) %>

<h1> ALL OF THE BLOG POSTINGS </h1>

<ul class="posts">
	<% @posts.each do |post| %>
		<li class="blog-post">Title: <%= post.title %></li>
		<li class="content-section">&nbsp &nbsp &nbsp &nbsp Content: 
		<%= post.content %> 
		<%= link_to("Edit Post", posts_edit_path(post))%>
		<%= link_to("Show Post", posts_show_path(post))%>
	<% end %>
</ul>

<%= paginate @posts %>

<!-- Alternate example from class 

app/views/posts/new.html.erb
<%= form_tag(posts_path, method: "post") do %>
	<h1>Create Post Here</h1>
	<div class="post-field">
	<%= label_tag("Title: ") %>
	<%= text_field_tag("title") %>
	</div>

	<div class="post-field">
		<%= label_tag("Content: ") %>
		<%= text_area_tag("content") %>
	</div>

	<%= button_tag("Create!") %>
<% end %>

app/views/posts/show.html.erb
<h1>CURRENT POST!?!</h1>
	
<div class="post-field">
	<%= label_tag("Title: ") %>
	<%= @post.title %>
</div>

<div class="post-field">
		<%= label_tag("Content: ") %>
		<%= @post.content %>
		<br/>
		<br/>
		<br/>
</div>

<%= form_tag(post_comments_path(@post.id)) do %>
	<div class="comment-field">
		<%= label_tag("Comment") %>
		<%= text_area_tag("body", nil, cols: 40, rows: 8) %>
		<br/>
	</div>

	<%= button_tag("Create Comment") %>
<% end %>

<% @post.comments.each do |comment| %>
	<div class ="post-comment" %>
	</div>
<% end %>